# Generated by Django 5.1.4 on 2025-01-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade2',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
