# Generated by Django 5.1.4 on 2025-01-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_quantidade2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade2',
        ),
    ]
