# Generated by Django 5.1.4 on 2025-01-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_quantidade2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao2',
        ),
    ]
