# Generated by Django 5.1.4 on 2025-01-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_e_hora', models.DateTimeField()),
                ('ID_Plano', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pendente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColaboradoresServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_servico', models.CharField(max_length=255)),
                ('Descricao', models.TextField()),
                ('Valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_servico', models.CharField(max_length=50)),
                ('planos', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
