# Generated by Django 5.1.4 on 2025-01-12 18:03

import django.db.models.deletion
from django.db import migrations, models

def add_tipservico(apps, schema_editor):
    TipoServico = apps.get_model('core', 'TipoServico')
    TipoServico.objects.get_or_create(tipo="Fisioterapia")
    TipoServico.objects.get_or_create(tipo="Pilates")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_blacklistedtoken'),
        ('usuarios', '0004_cliente_nome_cliente_sexo_colaborador_nome_and_more'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='Nome_servico',
            new_name='nome_servico',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='Valor',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='ID_Plano',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='planos',
        ),
        migrations.AlterUniqueTogether(
            name='colaboradoresservicos',
            unique_together={('colaborador', 'servico')},
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='core.servico')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='core.plano'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipo_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.tiposervico'),
        ), 
        migrations.RunPython(add_tipservico),
        
    ]
