# Generated by Django 5.1.4 on 2025-01-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tiposervico_rename_descricao_servico_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(choices=[('segunda-feira', 'Segunda-feira'), ('terca-feira', 'Terça-feira'), ('quarta-feira', 'Quarta-feira'), ('quinta-feira', 'Quinta-feira'), ('sexta-feira', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20),
        ),
    ]
