# Generated by Django 5.1.4 on 2025-01-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_horario_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status_pagamento',
            field=models.CharField(default='pendente', max_length=20),
        ),
    ]
