# Generated by Django 5.1.4 on 2025-01-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agendamento_status_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status_pagamento',
            field=models.CharField(default='Pendente', max_length=20),
        ),
    ]
