# Generated by Django 5.1.4 on 2025-01-02 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='referencias',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='password',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='referencias',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
