# Generated by Django 5.1.4 on 2025-01-05 17:21

import django.db.models.deletion
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_cliente_email_remove_cliente_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[usuarios.models.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[usuarios.models.validar_cpf]),
        ),
        migrations.AddField(
            model_name='cliente',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='usuarios.clinica'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='clinica',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='usuarios.clinica'),
            preserve_default=False,
        ),
    ]
