# Generated by Django 5.1.4 on 2025-01-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cliente_nome_cliente_sexo_colaborador_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
