# Generated by Django 5.1.4 on 2025-01-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_colaborador_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='data_nascimento',
            new_name='dt_nasc',
        ),
    ]
